<template>
  <div class="new-project">
      <div class="page-head"><button class="back" @click="$router.back()">‹ 返回</button><h2>新增项目</h2></div>
      <input ref="videoPicker" type="file" multiple accept="video/*,.mp4,.avi,.mov,.wmv,.mkv,.flv,.ts" hidden @change="addVideos([...$event.target.files])">
      <div class="workspace">
        <VideoUploadArea v-if="!videos.length" @select="addVideos" />
        <VideoListPanel v-else :videos="videos" :active-id="activeId" @upload="openVideoPicker" @select="activeId = $event" @remove="removeVideo" />
        <VideoPreview v-if="videos.length" :video="activeVideo" :show-select-box="subtitleSource === 'ocr' || subtitleErase" v-model:region="region" />
        <div v-else class="empty-preview">上传视频后显示预览</div>
        <section class="settings">
          <label>项目名称 <input v-model.trim="projectName" maxlength="20" placeholder="请输入"><em>{{ projectName.length }}/20</em></label>
          <label>源语言 <select v-model="sourceLanguage"><option value="">请选择</option><option v-for="l in languages" :key="l.value" :value="l.value">{{ l.label }}</option></select></label>
          <div class="setting-block"><div>字幕来源</div><div class="tabs"><AppTooltip v-for="s in subtitleSources" :key="s.value" :text="s.tooltip" placement="top"><button :class="{active: subtitleSource === s.value}" @click="subtitleSource=s.value">{{ s.label }}<small v-if="s.tag">（{{ s.tag }}）</small></button></AppTooltip></div>
            <div v-if="subtitleSource === 'upload'" class="subtitle-folder" @click="openSubtitlePicker"><input ref="subtitleInput" type="file" webkitdirectory directory multiple hidden @change="selectSubtitleFolder"><strong>请选择<span>字幕文件所在位置</span></strong><p>{{ subtitleFolder || '系统会自动匹配与视频文件同名的srt字幕文件' }}</p></div>
          </div>
          <SettingToggle label="角色识别" :value="roleRecognition" tooltip="20积分/分钟，智能识别对话角色；视频中存在多角色且需要译制配音时建议开启。" @change="roleRecognition=$event" />
          <p v-if="!roleRecognition" class="hint">关闭角色识别，译制配音时仅支持手动选择AI配音员</p>
          <SettingToggle label="人声背景音分离" :value="vocalSeparation" tooltip="20积分/分钟，视频存在背景音或音效时建议开启。" @change="vocalSeparation=$event" />
          <SettingToggle label="字幕擦除" :value="subtitleErase" tooltip="200积分/分钟，自动识别字幕内容并智能擦除。" @change="subtitleErase=$event" />
          <div class="estimate">积分消耗预估：<b>{{ totalPoints || '--' }}</b></div><button class="submit" :disabled="!videos.length" @click="submit">提交</button>
        </section>
      </div><SubmitProgressModal :visible="submitting" :current-step="step" :step-status="status" />
  </div>
</template>
<script>
import AppTooltip from '@/components/common/AppTooltip.vue'; import VideoUploadArea from '@/components/project/VideoUploadArea.vue'; import VideoListPanel from '@/components/project/VideoListPanel.vue'; import VideoPreview from '@/components/project/VideoPreview.vue'; import SubmitProgressModal from '@/components/project/SubmitProgressModal.vue'; import { SOURCE_LANGUAGES, SUBTITLE_SOURCES, MAX_VIDEO_COUNT } from '@/constants/project'; import { validateVideoFile, naturalSort } from '@/utils/videoValidator'; import { calcTotalPoints } from '@/utils/pointsCalculator'; import { fetchUserPoints, submitProjectTask } from '@/api/project'
const SettingToggle={props:['label','value','tooltip'],emits:['change'],components:{AppTooltip},template:'<div class="toggle-row"><AppTooltip :text="tooltip" placement="top"><span>{{label}} ⓘ</span></AppTooltip><button :class="{on:value}" @click="$emit(\'change\',!value)"><i></i></button></div>'}
export default { components:{AppTooltip,VideoUploadArea,VideoListPanel,VideoPreview,SubmitProgressModal,SettingToggle}, data:()=>({projectName:'',sourceLanguage:'',subtitleSource:'asr',roleRecognition:true,vocalSeparation:true,subtitleErase:false,videos:[],activeId:'',subtitleFolder:'',subtitleFiles:[],region:{x:.1,y:.65,w:.8,h:.2},submitting:false,step:0,status:'active',languages:SOURCE_LANGUAGES,subtitleSources:SUBTITLE_SOURCES}), computed:{activeVideo(){return this.videos.find(v=>v.id===this.activeId)||this.videos[0]},totalPoints(){return calcTotalPoints(this.videos,{subtitleSource:this.subtitleSource,roleRecognition:this.roleRecognition,vocalSeparation:this.vocalSeparation,subtitleErase:this.subtitleErase})}}, methods:{openVideoPicker(){this.$refs.videoPicker?.click()},addVideos(files){if(this.videos.length+files.length>MAX_VIDEO_COUNT)return alert('单次任务不能超过100个视频');const next=files.map((f,i)=>{const e=validateVideoFile(f);if(e.length){alert(`${f.name}${e.join('，')}，请检查修改`);return null}return{id:`${Date.now()}-${i}`,name:f.name,size:f.size,duration:f.duration||0,objectUrl:URL.createObjectURL(f),file:f}}).filter(Boolean);this.videos=[...this.videos,...next].sort(naturalSort);if(!this.activeId)this.activeId=this.videos[0]?.id||''},removeVideo(id){this.videos=this.videos.filter(v=>v.id!==id);this.activeId=this.videos[0]?.id||''},openSubtitlePicker(){this.$refs.subtitleInput.click()},selectSubtitleFolder(e){this.subtitleFiles=[...e.target.files];this.subtitleFolder=this.subtitleFiles[0]?.webkitRelativePath?.split('/')[0]||'已选择字幕文件夹'},async submit(){if(!this.projectName)return alert('请输入项目名称');if(!this.sourceLanguage)return alert('请选择源语言');if(this.subtitleSource==='upload'&&!this.subtitleFiles.length)return alert('请选择字幕文件所在位置');try{const r=await fetchUserPoints();const points=Number(r?.points??r?.data?.points??this.$store.state.user?.points??0);if(points<this.totalPoints)return alert('您的积分不足，无法提交此任务');this.submitting=true;this.step=0;await new Promise(r=>setTimeout(r,500));this.step=1;await new Promise(r=>setTimeout(r,500));this.step=2;await submitProjectTask({projectName:this.projectName,sourceLanguage:this.sourceLanguage,subtitleSource:this.subtitleSource,videos:this.videos.map(v=>({name:v.name,duration:v.duration})),roleRecognition:this.roleRecognition,vocalSeparation:this.vocalSeparation,subtitleErase:this.subtitleErase,region:this.region});this.status='done';setTimeout(()=>this.$router.push({name:'home'}),700)}catch(e){this.submitting=false;alert(e.message||'提交失败，请稍后重试')}}}}
</script>
<style scoped lang="scss">.new-project{position:fixed;inset:0;z-index:10;height:100vh;width:100vw;box-sizing:border-box;padding:28px 4vw 32px;background:#fff;display:flex;flex-direction:column;overflow:auto}.page-head{display:flex;align-items:center;gap:20px;margin-bottom:18px}.page-head h2{margin:0;font-size:24px}.back{font-size:14px;color:#666}.workspace{display:grid;grid-template-columns:250px minmax(360px,1fr) 500px;gap:24px;flex:1;min-height:0}.empty-preview{border:1px solid #eee;display:flex;align-items:center;justify-content:center;color:#aaa}.settings{padding:8px 4px}.settings>label{display:flex;align-items:center;gap:14px;margin-bottom:28px;font-size:16px}.settings input,.settings select{height:42px;border:1px solid #e5e5e5;border-radius:6px;padding:0 14px;font-size:14px;flex:1;min-width:0}.settings em{font-style:normal;color:#999;font-size:13px}.setting-block>div:first-child{margin-bottom:12px}.tabs{display:flex;background:#fafafa}.tabs button{flex:1;height:48px;color:#888}.tabs button.active{background:#fff;border-radius:8px;box-shadow:0 2px 8px #ddd;color:#333}.tabs small{font-size:12px}.subtitle-folder{border:1px solid #bbb;padding:18px;text-align:center;margin-top:4px;cursor:pointer}.subtitle-folder span{color:#2878ff}.subtitle-folder p{color:#999;font-size:12px}.toggle-row{display:flex;justify-content:space-between;align-items:center;margin-top:28px;font-size:16px}.toggle-row button{width:54px;height:30px;border-radius:20px;background:#ccc;padding:3px}.toggle-row button.on{background:#2878ff}.toggle-row button i{display:block;width:24px;height:24px;background:#fff;border-radius:50%;transition:.2s}.toggle-row button.on i{transform:translateX(24px)}.hint{font-size:12px;color:#999}.estimate{text-align:right;margin-top:44px}.estimate b{color:#ff7a00;margin-left:8px}.submit{width:100%;height:48px;background:#ed6200;color:#fff;border-radius:6px;margin-top:16px;font-size:18px}.submit:disabled{opacity:.45}@media(max-width:1100px){.workspace{grid-template-columns:210px 1fr}.settings{grid-column:1/-1}}@media(max-width:800px){.workspace{grid-template-columns:1fr}.settings{grid-column:auto}}</style>
